# Generated by Django 5.2.7 on 2025-10-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='technologies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='link',
            field=models.URLField(blank=True, help_text='GitHub or live URL'),
        ),
    ]
